import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawn } from 'node:child_process';
import pc from 'picocolors';
import { getClient, hasAuth } from '../client';
import { resolveEnvironment } from '../config';
import { printError, printInfo, printJson, printSuccess, printTable, printWarning } from '../formatter';
import { getVaultSession } from '../crypto/session';
import { LocalStore } from '../local/store';

export function parseEnvContent(raw: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!raw) return result;

  // If it's a JSON string of key-value pairs
  const trimmed = raw.trim();
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
    try {
      const parsed = JSON.parse(trimmed);
      if (typeof parsed === 'object' && parsed !== null) {
        for (const [k, v] of Object.entries(parsed)) {
          result[k] = typeof v === 'string' ? v : JSON.stringify(v);
        }
        return result;
      }
    } catch {}
  }

  // Parse standard line-by-line dotenv
  const lines = raw.split(/\r?\n/);
  for (const line of lines) {
    const trimmedLine = line.trim();
    if (!trimmedLine || trimmedLine.startsWith('#')) continue;

    const eqIndex = trimmedLine.indexOf('=');
    if (eqIndex === -1) continue;

    const key = trimmedLine.slice(0, eqIndex).trim();
    let val = trimmedLine.slice(eqIndex + 1).trim();

    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }

    if (key) {
      result[key] = val;
    }
  }

  return result;
}

export function formatEnvLines(vars: Record<string, string>, pure = true): string {
  const lines: string[] = [];
  if (!pure) {
    lines.push('# Generated by Kylrix CLI');
    lines.push(`# Timestamp: ${new Date().toISOString()}`);
    lines.push('');
  }
  for (const [k, v] of Object.entries(vars)) {
    const needsQuote = v.includes(' ') || v.includes('\n') || v.includes('"') || v.includes('#') || v.length === 0;
    const escaped = v.replace(/"/g, '\\"');
    lines.push(needsQuote ? `${k}="${escaped}"` : `${k}=${v}`);
  }
  return lines.join('\n');
}

export interface ResolvedEnvResult {
  id?: string;
  name?: string;
  isPublic?: boolean;
  variables: Record<string, string>;
  rawText: string;
}

export async function resolveEnvSource(
  idOrUrl: string,
  opts: { url?: string; token?: string; shareKey?: string; decrypt?: boolean } = {}
): Promise<ResolvedEnvResult> {
  let target = idOrUrl.trim();
  let extractedKey = opts.shareKey || null;

  // 1. Detect public vault URL or hash fragments:
  // e.g. https://www.kylrix.space/vault/public/sec_123#mykey or sec_123#mykey
  if (target.includes('/vault/public/')) {
    const parts = target.split('/vault/public/')[1].split(/[#\/?]/);
    target = parts[0];
    if (parts[1] && !extractedKey) extractedKey = parts[1];
  } else if (target.includes('/public/vault/')) {
    const parts = target.split('/public/vault/')[1].split(/[#\/?]/);
    target = parts[0];
    if (parts[1] && !extractedKey) extractedKey = parts[1];
  } else if (target.includes('#')) {
    const [idPart, keyPart] = target.split('#');
    target = idPart;
    if (keyPart && !extractedKey) extractedKey = keyPart;
  }

  const env = resolveEnvironment(opts);
  const isAuthed = hasAuth(opts);

  // If public or extracted key present, try public vault route first
  if (extractedKey || target.startsWith('http')) {
    try {
      const publicEndpoint = `${env.apiUrl}/api/v1/vault/public/${encodeURIComponent(target)}`;
      const query = new URLSearchParams({ format: 'env' });
      if (extractedKey) query.set('shareKey', extractedKey);

      const resp = await fetch(`${publicEndpoint}?${query.toString()}`, {
        headers: { Accept: 'application/json' },
      });

      if (resp.ok) {
        const data = await resp.json();
        const payload = data.data || data;
        const text = payload.envText || payload.customFields || payload.password || '';
        return {
          id: payload.id || target,
          name: payload.name || 'Public Vault Secret',
          isPublic: true,
          variables: parseEnvContent(text),
          rawText: text,
        };
      }
    } catch {}
  }

  // Next, try authenticated cloud fetch if logged in
  if (isAuthed) {
    try {
      const session = opts.decrypt !== false ? getVaultSession() : null;
      const client = getClient(opts);
      const res = await client.vault.get(target, {
        mek: session?.mekHex,
        format: 'env',
      });

      const text = res.envText || (typeof res.customFields === 'string' ? res.customFields : JSON.stringify(res.customFields || {})) || res.password || '';
      return {
        id: res.id || target,
        name: res.name || target,
        isPublic: Boolean(res.isPublic),
        variables: parseEnvContent(text),
        rawText: text,
      };
    } catch (cloudErr: any) {
      // Fall through to local check
    }
  }

  // Finally, fallback to local store
  try {
    const local = LocalStore.getVault(target);
    if (local) {
      const text = local.customFields
        ? typeof local.customFields === 'string'
          ? local.customFields
          : JSON.stringify(local.customFields)
        : local.password || '';
      return {
        id: local.id,
        name: local.name,
        isPublic: false,
        variables: parseEnvContent(text),
        rawText: text,
      };
    }
  } catch {}

  throw new Error(`Could not resolve environment secret "${idOrUrl}". Verify the secret ID, public link, or run \`kylrix vault unlock\`.`);
}

export async function getEnvCommand(
  idOrUrl: string,
  opts: {
    url?: string;
    token?: string;
    shareKey?: string;
    pure?: boolean;
    json?: boolean;
    decrypt?: boolean;
  }
) {
  try {
    const resolved = await resolveEnvSource(idOrUrl, opts);

    if (opts.json) {
      printJson(resolved.variables);
      return;
    }

    if (opts.pure) {
      console.log(formatEnvLines(resolved.variables, true));
      return;
    }

    console.log('\n' + pc.bold(resolved.name || 'Environment Variables'));
    console.log(pc.dim('─'.repeat(45)));
    console.log(`Secret ID: ${pc.cyan(resolved.id || idOrUrl)}`);
    console.log(`Access:    ${resolved.isPublic ? pc.green('Public / Shared') : pc.yellow('Vault Protected')}`);
    console.log(`Variables: ${Object.keys(resolved.variables).length} found`);
    console.log(pc.dim('─'.repeat(45)));
    console.log(formatEnvLines(resolved.variables, false));
    console.log();
  } catch (err: any) {
    printError(`Failed to get env "${idOrUrl}"`, err);
    process.exit(1);
  }
}

export async function pullEnvCommand(
  idOrUrl?: string,
  opts: {
    url?: string;
    token?: string;
    file?: string;
    append?: boolean;
    overwrite?: boolean;
    shareKey?: string;
    json?: boolean;
  } = {}
) {
  try {
    const targetFile = path.resolve(process.cwd(), opts.file || '.env');
    let varsToPull: Record<string, string> = {};
    let secretName = 'Active Environment';

    if (idOrUrl) {
      const resolved = await resolveEnvSource(idOrUrl, opts);
      varsToPull = resolved.variables;
      secretName = resolved.name || idOrUrl;
    } else {
      // Pull all env-tagged secrets from current workspace
      const isAuthed = hasAuth(opts);
      const items = isAuthed
        ? await getClient(opts).vault.list({ limit: 100 })
        : LocalStore.listVault();

      const envItems = (items || []).filter((v: any) => v.isEnv || v.itemType === 'env');
      if (envItems.length === 0) {
        throw new Error('No environment secrets found in the current workspace. Provide a secret ID or public share link.');
      }

      for (const item of envItems) {
        try {
          const res = await resolveEnvSource(item.id, opts);
          Object.assign(varsToPull, res.variables);
        } catch {}
      }
    }

    const keyCount = Object.keys(varsToPull).length;
    if (keyCount === 0) {
      printWarning('No environment variables found in specified secret.');
      return;
    }

    let existingVars: Record<string, string> = {};
    if (fs.existsSync(targetFile) && opts.append) {
      const existingRaw = fs.readFileSync(targetFile, 'utf-8');
      existingVars = parseEnvContent(existingRaw);
    }

    const merged = { ...existingVars, ...varsToPull };
    const content = formatEnvLines(merged, false) + '\n';

    fs.writeFileSync(targetFile, content, { encoding: 'utf-8', mode: 0o600 });

    if (opts.json) {
      printJson({
        file: targetFile,
        count: keyCount,
        keys: Object.keys(varsToPull),
      });
      return;
    }

    printSuccess(`Pulled ${keyCount} environment variable(s) from "${pc.bold(secretName)}" into ${pc.cyan(path.relative(process.cwd(), targetFile) || targetFile)}`);
    console.log(pc.dim(`Keys loaded: ${Object.keys(varsToPull).join(', ')}`));
  } catch (err: any) {
    printError('Failed to pull environment variables', err);
    process.exit(1);
  }
}

export async function runEnvCommand(
  idOrUrl: string,
  commandArgs: string[],
  opts: {
    url?: string;
    token?: string;
    shareKey?: string;
  }
) {
  try {
    if (!commandArgs || commandArgs.length === 0) {
      printError('Missing command to execute. Usage: `kylrix env run <id-or-url> -- <command...>`');
      process.exit(1);
    }

    const resolved = await resolveEnvSource(idOrUrl, opts);
    const varCount = Object.keys(resolved.variables).length;

    console.log(pc.dim(`⚡ Loaded ${varCount} environment variable(s) from "${resolved.name || idOrUrl}" into process memory`));

    const childEnv = { ...process.env, ...resolved.variables };
    const [bin, ...args] = commandArgs;

    const child = spawn(bin, args, {
      stdio: 'inherit',
      env: childEnv,
      shell: true,
    });

    child.on('exit', (code, signal) => {
      if (signal) {
        process.kill(process.pid, signal);
      } else {
        process.exit(code ?? 0);
      }
    });
  } catch (err: any) {
    printError(`Failed to run command with env "${idOrUrl}"`, err);
    process.exit(1);
  }
}

export async function pushEnvCommand(
  name: string,
  opts: {
    url?: string;
    token?: string;
    file?: string;
    workspace?: string;
    isPublic?: boolean;
    json?: boolean;
  }
) {
  try {
    const filePath = path.resolve(process.cwd(), opts.file || '.env');
    if (!fs.existsSync(filePath)) {
      throw new Error(`Environment file not found: ${filePath}`);
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = parseEnvContent(content);
    const keyCount = Object.keys(parsed).length;

    if (keyCount === 0) {
      printWarning(`Warning: ${filePath} contains no environment variables.`);
    }

    const isAuthed = hasAuth(opts);
    const session = getVaultSession();

    const payload = {
      name,
      customFields: content,
      isEnv: true,
      itemType: 'env',
      isPublic: Boolean(opts.isPublic),
    };

    const item = isAuthed
      ? await getClient(opts).vault.create(payload, {
          mek: session?.mekHex,
          workspaceId: opts.workspace,
        })
      : LocalStore.createVault(payload);

    if (opts.json) {
      printJson(item);
      return;
    }

    printSuccess(`Pushed ${keyCount} environment variable(s) from ${pc.dim(opts.file || '.env')} to secret "${pc.bold(item.name || item.id)}" (ID: ${pc.cyan(item.id)}) [${isAuthed ? 'Cloud' : 'Local'}]`);
  } catch (err: any) {
    printError('Failed to push environment variables to vault', err);
    process.exit(1);
  }
}

export async function listEnvsCommand(opts: {
  url?: string;
  token?: string;
  workspace?: string;
  json?: boolean;
  limit?: string;
  all?: boolean;
  page?: string;
}) {
  try {
    const isAuthed = hasAuth(opts);
    const limit = opts.all || opts.limit === '0' ? 0 : (opts.limit ? parseInt(opts.limit, 10) : 50);
    const page = opts.page ? Math.max(1, parseInt(opts.page, 10)) : 1;

    const allItems = isAuthed
      ? await getClient(opts).vault.list({ limit: 100, workspaceId: opts.workspace })
      : LocalStore.listVault();

    const envItems = (allItems || []).filter((v: any) => v.isEnv || v.itemType === 'env');
    const total = envItems.length;

    let sliced = envItems;
    if (limit > 0) {
      const offset = (page - 1) * limit;
      sliced = envItems.slice(offset, offset + limit);
    }

    if (opts.json) {
      printJson({ items: sliced, total, page, limit });
      return;
    }

    const rows = sliced.map((v: any) => ({
      id: v.id,
      name: v.name,
      variables: v.customFields ? Object.keys(parseEnvContent(typeof v.customFields === 'string' ? v.customFields : JSON.stringify(v.customFields))).length : '-',
      access: v.isPublic ? pc.green('public') : pc.dim('private'),
      mode: isAuthed ? (v.workspaceId || 'cloud') : pc.dim('local'),
      updatedAt: v.updatedAt?.substring(0, 10) || '',
    }));

    printTable(rows, ['id', 'name', 'variables', 'access', 'mode', 'updatedAt']);

    if (total > sliced.length) {
      const start = limit > 0 ? (page - 1) * limit + 1 : 1;
      const end = limit > 0 ? Math.min(page * limit, total) : total;
      console.log(pc.dim(`\nShowing ${start}–${end} of ${total} environment secret sets. Use --page <N> or --all to view more.`));
    }
  } catch (err: any) {
    printError('Failed to list environment secrets', err);
    process.exit(1);
  }
}
