export const APPWRITE_CONFIG = {
    ENDPOINT: process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT || 'https://api.kylrix.space/v1',
    PROJECT_ID: process.env.NEXT_PUBLIC_APPWRITE_PROJECT_ID || '67fe9627001d97e37ef3',
    DATABASE_ID: 'passwordManagerDb', // Consolidated database survivor
    NOTE_DATABASE_ID: 'passwordManagerDb',
    VAULT_DATABASE_ID: 'passwordManagerDb',
    FLOW_DATABASE_ID: 'passwordManagerDb',
    CONNECT_DATABASE_ID: 'passwordManagerDb',
    DATABASES: {
        NOTE: 'passwordManagerDb',
        VAULT: 'passwordManagerDb',
        FLOW: 'passwordManagerDb',
        CONNECT: 'passwordManagerDb',
        CHAT: 'passwordManagerDb',
        PASSWORD_MANAGER: 'passwordManagerDb',
        KYLRIXNOTE: 'passwordManagerDb',
        KYLRIXFLOW: 'passwordManagerDb'
    },
    TABLES: {
        // Flat aliases for common tables
        NOTES: '67ff05f3002502ef239e',
        TAGS: '67ff06280034908cf08a',
        TASKS: 'tasks',
        EVENTS: 'events',
        CALENDARS: 'calendars',
        EVENT_GUESTS: 'eventGuests',
        FOCUS_SESSIONS: 'focusSessions',
        MESSAGES: 'messages',
        PROFILES: 'profiles',
        KEYCHAIN: 'keychain',
        USER_RESOURCE_PINS: 'user_resource_pins',
        OBJECTS: 'objects',
        SWEPT: 'swept',
        TOKEN_REGISTRY: 'token_registry',
        WEB3_TRANSACTIONS: 'web3_transactions',
        NOSTR_IDENTITIES: 'nostr_identities',
        AGENT_PAYMENT_INTENTS: 'agent_payment_intents',

        NOTE: {
            USERS: '67ff05c900247b5673d3',
            NOTES: '67ff05f3002502ef239e',
            TAGS: '67ff06280034908cf08a',
            APIKEYS: '67ff064400263631ffe4',
            COMMENTS: 'comments',
            EXTENSIONS: 'extensions',
            REACTIONS: 'reactions',
            COLLABORATORS: 'collaborators',
            ACTIVITY_LOG: 'activityLog',
            SETTINGS: 'settings',
            SUBSCRIPTIONS: 'subscriptions',
            COUPONS: 'coupons',
            NOTE_TAGS: 'resource_tags',
            BLOGPOSTS: '67ff065a003e2bb950f7',
            WALLET_MAP: 'walletMap',
            NOTE_REVISIONS: 'note_revisions'
        },
        KYLRIXNOTE: {
            PROFILES: 'profiles',
            USERS: '67ff05c900247b5673d3',
            ACTIVITY_LOG: 'activityLog',
            WALLET_MAP: 'walletMap',
            NOTE_REVISIONS: 'note_revisions'
        },
        VAULT: {
            CREDENTIALS: 'credentials',
            TOTP_SECRETS: 'totpSecrets',
            FOLDERS: 'folders',
            SECURITY_LOGS: 'securityLogs',
            USER: 'user',
            KEYCHAIN: 'keychain',
            KEY_MAPPING: 'key_mapping',
            WALLETS: 'wallets',
            TOKEN_REGISTRY: 'token_registry',
            WEB3_TRANSACTIONS: 'web3_transactions'
        },
        PASSWORD_MANAGER: {
            KEYCHAIN: 'keychain',
            KEY_MAPPING: 'key_mapping',
            IDENTITIES: 'identities',
            WALLETS: 'wallets',
            TOKEN_REGISTRY: 'token_registry',
            WEB3_TRANSACTIONS: 'web3_transactions'
        },
        FLOW: {
            TASKS: 'tasks',
            EVENTS: 'events',
            GUESTS: 'eventGuests',
            COLLABORATORS: 'Collaborators',
            FORMS: 'forms',
            FORM_SUBMISSIONS: 'formSubmissions',
            AGENTS: 'agents',
            OBJECTS: 'objects',
            AGENT_PAYMENT_INTENTS: 'agent_payment_intents'
        },
        CONNECT: {
            USERS: 'users',
            PROFILES: 'profiles',
            CONVERSATIONS: 'conversations',
            CONVERSATION_MEMBERS: 'conversationMembers',
            MESSAGES: 'messages',
            JOIN_REQUESTS: 'joinRequests',
            MESSAGE_REACTIONS: 'messageReactions',
            EPOCHS: 'epochs',
            UNORGANIC_EMAILS: 'unorganic_emails',
            ACCOUNT_EVENTS: 'accountEvents',
            APP_ACTIVITY: 'app_activity',
            CALL_LINKS: 'calls',
            FOLLOWS: 'follows',
            MOMENTS: 'moments',
            INTERACTIONS: 'interactions',
            CONTACTS: 'contacts',
            KYLRIX_TOKEN_LEDGER: 'kylrix_token_ledger',
            ENGAGEMENT_VIEWS: 'engagement_views',
            ENGAGEMENT_VIEW_ROLLUPS: 'engagement_view_rollups',
            TELEGRAM_CONNECTIONS: 'telegram_connections',
            SOURCE_CONTROL: 'source_control',
            NOSTR_IDENTITIES: 'nostr_identities'
        },
        CHAT: {
            USERS: 'users',
            PROFILES: 'profiles',
            CONVERSATIONS: 'conversations',
            CONVERSATION_MEMBERS: 'conversationMembers',
            MESSAGES: 'messages',
            JOIN_REQUESTS: 'joinRequests',
            MESSAGE_REACTIONS: 'messageReactions',
            EPOCHS: 'epochs',
            UNORGANIC_EMAILS: 'unorganic_emails',
            ACCOUNT_EVENTS: 'accountEvents',
            APP_ACTIVITY: 'app_activity',
            CALL_LINKS: 'calls',
            FOLLOWS: 'follows',
            MOMENTS: 'moments',
            INTERACTIONS: 'interactions',
            CONTACTS: 'contacts',
            KYLRIX_TOKEN_LEDGER: 'kylrix_token_ledger',
            ENGAGEMENT_VIEWS: 'engagement_views',
            ENGAGEMENT_VIEW_ROLLUPS: 'engagement_view_rollups',
            TELEGRAM_CONNECTIONS: 'telegram_connections',
            SOURCE_CONTROL: 'source_control',
            NOSTR_IDENTITIES: 'nostr_identities'
        }
    },
    BUCKETS: {
        PROFILE_PICTURES: 'profile_pictures',
        GROUP_AVATARS: 'group_avatars',
        NOTES_ATTACHMENTS: 'notes_attachments',
        GENERAL_STORAGE: 'general_storage',
        BLOG_MEDIA: 'event_covers',
        EXTENSION_ASSETS: 'extension_assets',
        BACKUPS: 'backups',
        TEMP_UPLOADS: 'temp_uploads',
        /** Ephemeral file payloads for Send by Kylrix (provision in Appwrite; TTL ~7d via cron/cleanup). */
        SEND_EPHEMERAL: 'kylrix_send',
        MESSAGES: 'messages',
        VAULT_ATTACHMENTS: 'vault_attachments',
        FORM_MEDIA: 'form_media',
        FORM_ATTACHMENTS: 'form_attachments',
        CHAT_UPLOADS: 'chat_uploads',
        TASK_ATTACHMENTS: 'notes_attachments', // Alias
        EVENT_COVERS: 'event_covers', // Alias
        VOICE: 'voice'
    },
    FUNCTIONS: {
        PERMISSION_UPDATER: '69c0ff79001b60e664d2',
        CLAIM_GHOST_NOTES: 'claim-ghost-notes',
        SEARCH_USERS: '69a582720012957d2027',
        SYNC_USER_PROFILE: '69a583ac002b674685b0',
        NOTIFY_ON_SHARE: '69a58c1c001c39695bf6',
        NOTIFY_ON_SOCIAL_ACTIVITY: '69a6bf6200180e70aca1',
        FLOW_EVENT_SYNC: '69a6c28f003bb7d7e054',
        LOG_SECURITY_EVENT: '69a6c45a002085baa8dd',
        SYNC_SUBSCRIPTION_STATUS: '69a6c56d00203438232c',
        ACCOUNT_CLEANUP: '69a6c6fc001dc877979d',
        CONNECT_CALL_CLEANUP: '69a6c841000b2c5aaae3',
        DATA_PORTER: 'data-porter',
        WEB3_WALLET: '68e76f25001e8b80a6c2',
        FLOW_AGENT_ORCHESTRATOR: 'flow-agent-orchestrator',
        ECOSYSTEM_CONTEXT_AGGREGATOR: 'ecosystem-context-aggregator',
        AGENT_ACTION_GUARDRAIL: 'agent-action-guardrail'
    },
    SYSTEM: {
        DOMAIN: 'kylrix.space',
        AUTH_SUBDOMAIN: 'accounts',
        RP_NAME: 'kylrix',
        RP_ID: 'kylrix.space'
    }
};

export const KYLRIX_AUTH_URI = `https://${APPWRITE_CONFIG.SYSTEM.AUTH_SUBDOMAIN}.${APPWRITE_CONFIG.SYSTEM.DOMAIN}`;
export const KYLRIX_DOMAIN = APPWRITE_CONFIG.SYSTEM.DOMAIN;
export const KYLRIX_AUTH_SUBDOMAIN = APPWRITE_CONFIG.SYSTEM.AUTH_SUBDOMAIN;
